### PR TITLE
Add changes from hic-infra fork

### PR DESCRIPTION
**Pull request by manics**
This contains support for all changes from the hic-infra fork. Additional parameters may be required to enable the optional HIC-TRE features.

~~These changes have not yet been reviewed/checked for compatibility with TREEHOOSE. The main changes to be reviewed are the `*.py` files.~~

@AaronJackson

### CODE REVIEW

**Comment by AaronJackson** [comment]
Agreed - we make the URL expiry configurable. 
I'm hoping Martin will do a review of my changes. He also has some changes in "martinsAttempt" which need testing and reviewing.

**Comment by AaronJackson** [comment]
This looks ok I think - there was something for adding the project to the sns notification but I'm not sure I can see this in there.  Was this intentionally not moved over?

**Comment by manics** [comment]
This is the only diff (presigned link needs to be configurable)
```diff
diff --git a/egress_backend/lambda/egress_api/download_data.py b/egress_backend/lambda/egress_api/download_data.py
index 28dea07..19ccc56 100644
--- a/egress_backend/lambda/egress_api/download_data.py
+++ b/egress_backend/lambda/egress_api/download_data.py
@@ -37,9 +37,6 @@ max_downloads_allowed = os.environ["MAX_DOWNLOADS_ALLOWED"]
 @logger.inject_lambda_context(log_event=True)
 def download_data(arguments: str, context: Any):
 
-    # Allow the presigned link to last 3 days
-    link_life = 3 * 24 * 3600
-
     try:
         # Static filename
         file = "egress_data.zip"
@@ -68,7 +65,7 @@ def download_data(arguments: str, context: Any):
             # Generate presign URL
             presign = s3_client.generate_presigned_url(
                 "get_object",
-                ExpiresIn=link_life,
+                ExpiresIn=3600,
                 Params={"Bucket": bucket, "Key": object_key},
             )
             logger.debug("Presign URL generated: %s", presign)
```
Note this PR isn't ready yet since it's mostly a reformatted copy of the HIC-TRE fork. It needs some changes to also work with TREEHOOSE

**Comment by manics** [comment]
## Diff from TREEHOOSE:

<details>

```diff
diff --git a/egress_backend/egress_backend_stack.py b/egress_backend/egress_backend_stack.py
index efe5db6..7a80afe 100644
--- a/egress_backend/egress_backend_stack.py
+++ b/egress_backend/egress_backend_stack.py
@@ -36,6 +36,25 @@ from components.email_identity.email_identity_verification_cr import (
 )
 
 
+def from_bool_string(s, rtype):
+    """
+    Returns:
+        rtype=str: 'true' or 'false'
+        type=bool: true or false
+    """
+    if rtype in (str, bool):
+        raise ValueError(f"Invalid return type: {rtype}")
+    if s.lower() == "true":
+        if rtype == str:
+            return "true"
+        return True
+    if s.lower() == "false":
+        if rtype == str:
+            return "false"
+        return False
+    raise ValueError(f"Invalid boolean string: {s}")
+
+
 class EgressBackendStack(cdk.Stack):
     def __init__(
         self, scope: cdk.Construct, construct_id: str, env_id: str, **kwargs
@@ -79,20 +98,39 @@ class EgressBackendStack(cdk.Stack):
             self.node.try_get_context(env_id).get("swb_egress_store_db_table"),
         )
 
-        # Import existing DataLake target Bucket
-        datalake_bucket = s3.Bucket.from_bucket_arn(
-            self,
-            "datalake-target-bucket",
-            self.node.try_get_context(env_id).get("datalake_target_bucket_arn"),
+        datalake_target_bucket_arn = self.node.try_get_context(env_id).get(
+            "datalake_target_bucket_arn"
         )
-
-        # Import existing DataLake target Bucket KMS key
-        datalake_bucket_kms_key = kms.Key.from_key_arn(
-            self,
-            "datalake-target-bucket-kms-key",
-            self.node.try_get_context(env_id).get("datalake_target_bucket_kms_arn"),
+        datalake_target_bucket_kms_arn = self.node.try_get_context(env_id).get(
+            "datalake_target_bucket_kms_arn"
         )
 
+        if datalake_target_bucket_arn and datalake_target_bucket_kms_arn:
+            datalake_target_provided = True
+        elif not datalake_target_bucket_arn and not datalake_target_bucket_kms_arn:
+            datalake_target_provided = False
+        else:
+            raise ValueError(
+                "Either both or neither of datalake_target_bucket_arn and datalake_target_bucket_kms_arn required"
+            )
+
+        if datalake_target_provided:
+            # Import existing DataLake target Bucket
+            # datalake_bucket = s3.Bucket.from_bucket_arn(
+            egress_target_bucket = s3.Bucket.from_bucket_arn(
+                self,
+                "datalake-target-bucket",
+                self.node.try_get_context(env_id).get("datalake_target_bucket_arn"),
+            )
+
+            # Import existing DataLake target Bucket KMS key
+            # datalake_bucket_kms_key = kms.Key.from_key_arn(
+            egress_target_bucket_kms_key = kms.Key.from_key_arn(
+                self,
+                "datalake-target-bucket-kms-key",
+                self.node.try_get_context(env_id).get("datalake_target_bucket_kms_arn"),
+            )
+
         # Variable for the project name
         tre_project = self.node.try_get_context(env_id)["resource_tags"]["ProjectName"]
 
@@ -116,6 +154,17 @@ class EgressBackendStack(cdk.Stack):
             "tre_admin_email_address"
         )
 
+        # Optional AWS Account ID that the IG will use to look at egress data requests
+        ig_workspaces_account = self.node.try_get_context(env_id).get(
+            "ig_workspaces_account"
+        )
+
+        # Customised SWB with access points
+        use_s3_access_points = from_bool_string(
+            self.node.try_get_context(env_id).get("use_s3_access_points"), bool
+        )
+
+        # The code that defines your stack goes here
         this_dir = path.dirname(__file__)
 
         # Create KMS keys for resources
@@ -123,6 +172,24 @@ class EgressBackendStack(cdk.Stack):
             self, "Egress-S3-Key", alias="alias/Egress-S3-Key", enable_key_rotation=True
         )
 
+        if ig_workspaces_account:
+            s3_kms_key.add_to_resource_policy(
+                iam.PolicyStatement(
+                    sid="AllowAccessForIGWorkspaces",
+                    effect=iam.Effect.ALLOW,
+                    principals=[
+                        iam.AccountPrincipal(ig_workspaces_account),
+                    ],
+                    resources=[
+                        "*",
+                    ],
+                    actions=[
+                        "kms:GenerateDataKey",
+                        "kms:Decrypt",
+                    ],
+                )
+            )
+
         dynamodb_kms_key = kms.Key(
             self,
             "Egress-DynamoDB-Key",
@@ -148,7 +215,9 @@ class EgressBackendStack(cdk.Stack):
             env_id=env_id,
             configuration_set_name=ses_config_set_name,
         )
-        ses_monitoring_sns_topic = sns.Topic(self, "SES-Monitoring-Notifications", master_key=sns_kms_key)
+        ses_monitoring_sns_topic = sns.Topic(
+            self, "SES-Monitoring-Notifications", master_key=sns_kms_key
+        )
 
         sns_configuration_set_destination = (
             EmailConfigurationSetEventDestinationCustomResource(
@@ -293,10 +362,79 @@ class EgressBackendStack(cdk.Stack):
             server_access_logs_prefix="egress_staging_logs",
         )
 
+        if use_s3_access_points:
+            egress_staging_bucket.add_to_resource_policy(
+                permission=iam.PolicyStatement(
+                    sid="Delegate fine grained permissions to access points",
+                    effect=iam.Effect.ALLOW,
+                    principals=[iam.AnyPrincipal()],
+                    actions=["s3:*"],
+                    resources=[
+                        f"{egress_staging_bucket.bucket_arn}/*",
+                        f"{egress_staging_bucket.bucket_arn}",
+                    ],
+                    conditions={
+                        "StringEquals": {"s3:DataAccessPointAccount": self.account}
+                    },
+                )
+            )
+
+            egress_staging_bucket_access_point = s3.CfnAccessPoint(
+                self,
+                "rEgressStagingBucketAccessPoint",
+                bucket=egress_staging_bucket.bucket_name,
+                name="egress-staging-bucket-access-point",
+                public_access_block_configuration=s3.CfnAccessPoint.PublicAccessBlockConfigurationProperty(
+                    block_public_acls=True,
+                    block_public_policy=True,
+                    ignore_public_acls=True,
+                    restrict_public_buckets=True,
+                ),
+            )
+
+            egress_staging_bucket_access_point.policy = iam.PolicyDocument(
+                statements=[
+                    iam.PolicyStatement(
+                        sid="S3ExternalReadAccess",
+                        effect=iam.Effect.ALLOW,
+                        principals=[iam.AccountPrincipal(ig_workspaces_account)],
+                        actions=["s3:GetObject"],
+                        resources=[
+                            f"arn:aws:s3:{self.region}:{self.account}:accesspoint/egress-staging-bucket-access-point/object/*",
+                        ],
+                    ),
+                    iam.PolicyStatement(
+                        sid="ListBucketForEgressData",
+                        effect=iam.Effect.ALLOW,
+                        principals=[iam.AccountPrincipal(ig_workspaces_account)],
+                        actions=["s3:ListBucket"],
+                        resources=[
+                            f"arn:aws:s3:{self.region}:{self.account}:accesspoint/egress-staging-bucket-access-point",
+                        ],
+                    ),
+                ]
+            )
+
         # Add dataset tags to bucket
         for tag_key, tag_value in self.node.try_get_context(env_id)["dataset"].items():
             Tags.of(egress_staging_bucket).add(tag_key, tag_value)
 
+        if not datalake_target_provided:
+            # Add Egress Target Bucket
+            egress_target_bucket = s3.Bucket(
+                self,
+                "Egress-Target-Bucket",
+                encryption=s3.BucketEncryption.KMS,
+                encryption_key=s3_kms_key,
+                enforce_ssl=True,
+                block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
+                server_access_logs_bucket=access_logs_bucket,
+                server_access_logs_prefix="egress_target_logs",
+                versioned=True,
+                bucket_key_enabled=True,
+            )
+            egress_target_bucket_kms_key = s3_kms_key
+
         # Add Amplify App
         amplify_branch_name = "main"
         amplify_app = amplify.App(self, "EgressFrontendApp")
@@ -427,6 +565,9 @@ class EgressBackendStack(cdk.Stack):
                 "s3_swb_object_metadata_version": sfn_tasks.DynamoAttributeValue.from_string(
                     sfn.JsonPath.string_at("$.ver")
                 ),
+                "is_single_approval_enabled": sfn_tasks.DynamoAttributeValue.from_string(
+                    sfn.JsonPath.string_at("$.is_single_approval_enabled")
+                ),
             },
             table=egress_requests_table,
             # Set to None/Null so that original input gets passed on to the next task since we do not
@@ -676,6 +817,7 @@ class EgressBackendStack(cdk.Stack):
             ),
             message=sfn.TaskInput.from_object(
                 {
+                    "Workspace ID": sfn.JsonPath.string_at("$.workspace_id"),
                     "Egress Request ID": sfn.JsonPath.string_at("$.egress_request_id"),
                     "Researcher Email": sfn.JsonPath.string_at("$.created_by_email"),
                     "Egress Object File Types": sfn.JsonPath.string_at(
@@ -695,6 +837,7 @@ class EgressBackendStack(cdk.Stack):
             ),
             message=sfn.TaskInput.from_object(
                 {
+                    "Workspace ID": sfn.JsonPath.string_at("$.workspace_id"),
                     "Egress Request ID": sfn.JsonPath.string_at("$.egress_request_id"),
                     "Researcher Email": sfn.JsonPath.string_at("$.created_by_email"),
                     "Information Governance": sfn.JsonPath.string_at(
@@ -866,8 +1009,8 @@ class EgressBackendStack(cdk.Stack):
             memory_size=1024,
             environment={
                 "EGRESS_STAGING_BUCKET": egress_staging_bucket.bucket_name,
-                "EGRESS_DATALAKE_BUCKET": datalake_bucket.bucket_name,
-                "EGRESS_DATALAKE_BUCKET_KMS_KEY": datalake_bucket_kms_key.key_arn,
+                "EGRESS_DATALAKE_BUCKET": egress_target_bucket.bucket_name,
+                "EGRESS_DATALAKE_BUCKET_KMS_KEY": egress_target_bucket_kms_key.key_arn,
                 "EFS_MOUNT_PATH": efs_mount_path + "/",  # Need the extra slash
                 "REGION": self.region,
             },
@@ -878,13 +1021,13 @@ class EgressBackendStack(cdk.Stack):
         )
 
         # Grant copy lambda function permission to write to datalake bucket
-        datalake_bucket.grant_put(copy_egress_candidates_to_datalake_function)
+        egress_target_bucket.grant_put(copy_egress_candidates_to_datalake_function)
 
         # Grant copy lambda function permission to use KMS key of the staging bucket
         s3_kms_key.grant_decrypt(copy_egress_candidates_to_datalake_function)
 
         # Grant copy lambda function permission to use KMS key of the datalake bucket
-        datalake_bucket_kms_key.grant_encrypt_decrypt(
+        egress_target_bucket_kms_key.grant_encrypt_decrypt(
             copy_egress_candidates_to_datalake_function
         )
 
@@ -893,9 +1036,19 @@ class EgressBackendStack(cdk.Stack):
         egress_staging_bucket.grant_delete(copy_egress_candidates_to_datalake_function)
 
         # Define egress copy_to_staging Step Function task
-        copy_to_datalake_task = sfn_tasks.LambdaInvoke(
+        copy_to_datalake_task_rit = sfn_tasks.LambdaInvoke(
+            self,
+            "Copy Approved Objects To Datalake - RIT",
+            lambda_function=copy_egress_candidates_to_datalake_function,
+            result_selector={
+                "transferred_to_datalake": sfn.JsonPath.string_at("$.Payload")
+            },
+            result_path="$.copy_to_datalake_result",
+        )
+
+        copy_to_datalake_task_ig = sfn_tasks.LambdaInvoke(
             self,
-            "Copy Approved Objects To Datalake",
+            "Copy Approved Objects To Datalake - IGLead",
             lambda_function=copy_egress_candidates_to_datalake_function,
             result_selector={
                 "transferred_to_datalake": sfn.JsonPath.string_at("$.Payload")
@@ -1058,6 +1211,11 @@ class EgressBackendStack(cdk.Stack):
             iam_action="ses:sendEmail",
         )
 
+        # This is passed around the lambda so must be a string
+        is_single_approval_enabled = from_bool_string(
+            self.node.try_get_context(env_id).get("enable_single_approval"), str
+        )
+
         # Define Egress Workflow Step Function
         workflow_log_group = logs.LogGroup(self, "ApprovalWorkflowLogs")
         data_egress_step_function = sfn.StateMachine(
@@ -1072,8 +1230,13 @@ class EgressBackendStack(cdk.Stack):
             .next(ig_update_request_in_db_task)
             .next(
                 check_ig_approval.when(
-                    sfn.Condition.string_matches(
-                        "$.information_governance.result.egress_status", "*APPROVED"
+                    sfn.Condition.and_(
+                        sfn.Condition.string_matches(
+                            "$.information_governance.result.egress_status", "*APPROVED"
+                        ),
+                        sfn.Condition.string_matches(
+                            "$.is_single_approval_enabled", "false"
+                        ),
                     ),
                     notify_rit_reviewer_task.next(rit_decision_task)
                     .next(rit_update_request_in_db_task)
@@ -1083,7 +1246,7 @@ class EgressBackendStack(cdk.Stack):
                                 "$.research_it.result.rit_reviewer_2_decision",
                                 "APPROVED",
                             ),
-                            copy_to_datalake_task.next(
+                            copy_to_datalake_task_rit.next(
                                 update_request_in_egress_store_db_rit_task
                             ),
                         ).when(
@@ -1097,6 +1260,19 @@ class EgressBackendStack(cdk.Stack):
                         )
                     ),
                 )
+                .when(
+                    sfn.Condition.and_(
+                        sfn.Condition.string_matches(
+                            "$.information_governance.result.egress_status", "*APPROVED"
+                        ),
+                        sfn.Condition.string_matches(
+                            "$.is_single_approval_enabled", "true"
+                        ),
+                    ),
+                    copy_to_datalake_task_ig.next(
+                        update_request_in_egress_store_db_iglead_task
+                    ),
+                )
                 .when(
                     sfn.Condition.string_matches(
                         "$.information_governance.result.egress_status", "*REJECTED"
@@ -1153,6 +1329,7 @@ class EgressBackendStack(cdk.Stack):
                 "EGRESS_APP_URL": egress_app_url,
                 "EGRESS_APP_ADMIN_EMAIL": tre_admin_email_address,
                 "REGION": self.region,
+                "IS_SINGLE_APPROVAL_ENABLED": is_single_approval_enabled,
             },
         )
 
@@ -1180,21 +1357,24 @@ class EgressBackendStack(cdk.Stack):
                 "TABLE": egress_requests_table.table_name,
                 "STEP_FUNCTION_ARN": data_egress_step_function.state_machine_arn,
                 "REGION": self.region,
-                "DATALAKE_BUCKET": datalake_bucket.bucket_name,
+                "DATALAKE_BUCKET": egress_target_bucket.bucket_name,
                 "REVIEWER_LIST": json.dumps(
                     self.node.try_get_context(env_id).get("egress_reviewer_roles")
                 ),
                 "MAX_DOWNLOADS_ALLOWED": self.node.try_get_context(env_id).get(
                     "max_downloads_allowed"
                 ),
+                "DOWNLOAD_EXPIRY_SECONDS": self.node.try_get_context(env_id).get(
+                    "download_expiry_seconds"
+                ),
             },
         )
 
         # Grant the api lambda permission to access the datalake bucket
-        datalake_bucket.grant_read(egress_api_handler)
+        egress_target_bucket.grant_read(egress_api_handler)
 
         # Grant api lambda function permission to use KMS key of the datalake bucket
-        datalake_bucket_kms_key.grant_decrypt(egress_api_handler)
+        s3_kms_key.grant_decrypt(egress_api_handler)
 
         # Grant the api lambda permission to access the DynamoDB table
         egress_requests_table.grant_read_write_data(egress_api_handler)
@@ -1614,20 +1794,6 @@ class EgressBackendStack(cdk.Stack):
             description="The URL for the Egress App.",
         )
 
-        cdk.CfnOutput(
-            self,
-            "EgressReviewerRole1",
-            value=self.node.try_get_context(env_id).get("egress_reviewer_roles")[0],
-            description="The Cognito group name for reviewer type 1.",
-        )
-
-        cdk.CfnOutput(
-            self,
-            "EgressReviewerRole2",
-            value=self.node.try_get_context(env_id).get("egress_reviewer_roles")[1],
-            description="The Cognito group name for reviewer type 2.",
-        )
-
         cdk.CfnOutput(
             self,
             "MaxDownloadsAllowed",
@@ -1635,6 +1801,17 @@ class EgressBackendStack(cdk.Stack):
             description="Max downloads allowed parameter provided.",
         )
 
+        for idx, role in enumerate(
+            self.node.try_get_context(env_id).get("egress_reviewer_roles")
+        ):
+
+            cdk.CfnOutput(
+                self,
+                f"EgressReviewerRole{idx+1}",
+                value=role,
+                description=f"The Cognito group name for reviewer type {role}.",
+            )
+
         cdk.CfnOutput(
             self,
             "AppSyncGraphQLURL",
@@ -1669,3 +1846,32 @@ class EgressBackendStack(cdk.Stack):
             value=egress_webapp_bucket.bucket_name,
             description="The name for the S3 bucket created to host the packaged frontend app.",
         )
+
+        cdk.CfnOutput(
+            self,
+            "EgressWebAppTargetS3BucketName",
+            value=egress_target_bucket.bucket_name,
+            description="The name for the S3 bucket to store the final egress data.",
+        )
+
+        cdk.CfnOutput(
+            self,
+            "EgressStagingS3BucketName",
+            value=egress_staging_bucket.bucket_name,
+            description="The name for the egress staging S3 bucket to review files for egress approvals",
+        )
+
+        cdk.CfnOutput(
+            self,
+            "EgressStagingS3BucketKeyArn",
+            value=s3_kms_key.key_arn,
+            description="KMS Key ARN for egress staging s3 bucket",
+        )
+
+        if use_s3_access_points:
+            cdk.CfnOutput(
+                self,
+                "EgressStagingS3BucketAccessPointArn",
+                value=egress_staging_bucket_access_point.attr_arn,
+                description="Egress staging bucket access point arn",
+            )
```
</details>

## Diff from hic-tre:

<details>

```diff
diff --git a/egress_backend/egress_backend_stack.py b/egress_backend/egress_backend_stack.py
index 49865ab..7a80afe 100644
--- a/egress_backend/egress_backend_stack.py
+++ b/egress_backend/egress_backend_stack.py
@@ -36,6 +36,25 @@ from components.email_identity.email_identity_verification_cr import (
 )
 
 
+def from_bool_string(s, rtype):
+    """
+    Returns:
+        rtype=str: 'true' or 'false'
+        type=bool: true or false
+    """
+    if rtype in (str, bool):
+        raise ValueError(f"Invalid return type: {rtype}")
+    if s.lower() == "true":
+        if rtype == str:
+            return "true"
+        return True
+    if s.lower() == "false":
+        if rtype == str:
+            return "false"
+        return False
+    raise ValueError(f"Invalid boolean string: {s}")
+
+
 class EgressBackendStack(cdk.Stack):
     def __init__(
         self, scope: cdk.Construct, construct_id: str, env_id: str, **kwargs
@@ -79,6 +98,39 @@ class EgressBackendStack(cdk.Stack):
             self.node.try_get_context(env_id).get("swb_egress_store_db_table"),
         )
 
+        datalake_target_bucket_arn = self.node.try_get_context(env_id).get(
+            "datalake_target_bucket_arn"
+        )
+        datalake_target_bucket_kms_arn = self.node.try_get_context(env_id).get(
+            "datalake_target_bucket_kms_arn"
+        )
+
+        if datalake_target_bucket_arn and datalake_target_bucket_kms_arn:
+            datalake_target_provided = True
+        elif not datalake_target_bucket_arn and not datalake_target_bucket_kms_arn:
+            datalake_target_provided = False
+        else:
+            raise ValueError(
+                "Either both or neither of datalake_target_bucket_arn and datalake_target_bucket_kms_arn required"
+            )
+
+        if datalake_target_provided:
+            # Import existing DataLake target Bucket
+            # datalake_bucket = s3.Bucket.from_bucket_arn(
+            egress_target_bucket = s3.Bucket.from_bucket_arn(
+                self,
+                "datalake-target-bucket",
+                self.node.try_get_context(env_id).get("datalake_target_bucket_arn"),
+            )
+
+            # Import existing DataLake target Bucket KMS key
+            # datalake_bucket_kms_key = kms.Key.from_key_arn(
+            egress_target_bucket_kms_key = kms.Key.from_key_arn(
+                self,
+                "datalake-target-bucket-kms-key",
+                self.node.try_get_context(env_id).get("datalake_target_bucket_kms_arn"),
+            )
+
         # Variable for the project name
         tre_project = self.node.try_get_context(env_id)["resource_tags"]["ProjectName"]
 
@@ -102,6 +154,16 @@ class EgressBackendStack(cdk.Stack):
             "tre_admin_email_address"
         )
 
+        # Optional AWS Account ID that the IG will use to look at egress data requests
+        ig_workspaces_account = self.node.try_get_context(env_id).get(
+            "ig_workspaces_account"
+        )
+
+        # Customised SWB with access points
+        use_s3_access_points = from_bool_string(
+            self.node.try_get_context(env_id).get("use_s3_access_points"), bool
+        )
+
         # The code that defines your stack goes here
         this_dir = path.dirname(__file__)
 
@@ -110,24 +172,23 @@ class EgressBackendStack(cdk.Stack):
             self, "Egress-S3-Key", alias="alias/Egress-S3-Key", enable_key_rotation=True
         )
 
-        s3_kms_key.add_to_resource_policy(
-            iam.PolicyStatement(
-                sid="AllowAccessForIGWorkspaces",
-                effect=iam.Effect.ALLOW,
-                principals=[
-                    iam.AccountPrincipal(self.node.try_get_context(
-                                env_id
-                            ).get("ig_workspaces_account")),
-                ],
-                resources=[
-                    "*",
-                ],
-                actions=[
-                    "kms:GenerateDataKey",
-                    "kms:Decrypt",
-                ],
+        if ig_workspaces_account:
+            s3_kms_key.add_to_resource_policy(
+                iam.PolicyStatement(
+                    sid="AllowAccessForIGWorkspaces",
+                    effect=iam.Effect.ALLOW,
+                    principals=[
+                        iam.AccountPrincipal(ig_workspaces_account),
+                    ],
+                    resources=[
+                        "*",
+                    ],
+                    actions=[
+                        "kms:GenerateDataKey",
+                        "kms:Decrypt",
+                    ],
+                )
             )
-        )
 
         dynamodb_kms_key = kms.Key(
             self,
@@ -301,81 +362,78 @@ class EgressBackendStack(cdk.Stack):
             server_access_logs_prefix="egress_staging_logs",
         )
 
-        egress_staging_bucket.add_to_resource_policy(
-            permission=iam.PolicyStatement(
-                sid="Delegate fine grained permissions to access points",
-                effect=iam.Effect.ALLOW,
-                principals=[iam.AnyPrincipal()],
-                actions=["s3:*"],
-                resources=[
-                    f"{egress_staging_bucket.bucket_arn}/*",
-                    f"{egress_staging_bucket.bucket_arn}",
-                ],
-                conditions={
-                    "StringEquals": {
-                        "s3:DataAccessPointAccount": self.account
-                    }
-                },
-            )
-        )
-
-        egress_staging_bucket_access_point = s3.CfnAccessPoint(
-            self,
-            "rEgressStagingBucketAccessPoint",
-            bucket=egress_staging_bucket.bucket_name,
-            name="egress-staging-bucket-access-point",
-            public_access_block_configuration=s3.CfnAccessPoint.PublicAccessBlockConfigurationProperty(
-                block_public_acls=True,
-                block_public_policy=True,
-                ignore_public_acls=True,
-                restrict_public_buckets=True,
-            ),
-        )
-
-        egress_staging_bucket_access_point.policy = iam.PolicyDocument(
-            statements=[
-                iam.PolicyStatement(
-                    sid="S3ExternalReadAccess",
-                    effect=iam.Effect.ALLOW,
-                    principals=[iam.AccountPrincipal(self.node.try_get_context(
-                                env_id
-                            ).get("ig_workspaces_account"))],
-                    actions=["s3:GetObject"],
-                    resources=[
-                        f"arn:aws:s3:{self.region}:{self.account}:accesspoint/egress-staging-bucket-access-point/object/*",
-                    ],
-                ),
-                iam.PolicyStatement(
-                    sid="ListBucketForEgressData",
+        if use_s3_access_points:
+            egress_staging_bucket.add_to_resource_policy(
+                permission=iam.PolicyStatement(
+                    sid="Delegate fine grained permissions to access points",
                     effect=iam.Effect.ALLOW,
-                    principals=[iam.AccountPrincipal(self.node.try_get_context(
-                                env_id
-                            ).get("ig_workspaces_account"))],
-                    actions=["s3:ListBucket"],
+                    principals=[iam.AnyPrincipal()],
+                    actions=["s3:*"],
                     resources=[
-                        f"arn:aws:s3:{self.region}:{self.account}:accesspoint/egress-staging-bucket-access-point",
+                        f"{egress_staging_bucket.bucket_arn}/*",
+                        f"{egress_staging_bucket.bucket_arn}",
                     ],
+                    conditions={
+                        "StringEquals": {"s3:DataAccessPointAccount": self.account}
+                    },
+                )
+            )
+
+            egress_staging_bucket_access_point = s3.CfnAccessPoint(
+                self,
+                "rEgressStagingBucketAccessPoint",
+                bucket=egress_staging_bucket.bucket_name,
+                name="egress-staging-bucket-access-point",
+                public_access_block_configuration=s3.CfnAccessPoint.PublicAccessBlockConfigurationProperty(
+                    block_public_acls=True,
+                    block_public_policy=True,
+                    ignore_public_acls=True,
+                    restrict_public_buckets=True,
                 ),
-            ]
-        )
+            )
+
+            egress_staging_bucket_access_point.policy = iam.PolicyDocument(
+                statements=[
+                    iam.PolicyStatement(
+                        sid="S3ExternalReadAccess",
+                        effect=iam.Effect.ALLOW,
+                        principals=[iam.AccountPrincipal(ig_workspaces_account)],
+                        actions=["s3:GetObject"],
+                        resources=[
+                            f"arn:aws:s3:{self.region}:{self.account}:accesspoint/egress-staging-bucket-access-point/object/*",
+                        ],
+                    ),
+                    iam.PolicyStatement(
+                        sid="ListBucketForEgressData",
+                        effect=iam.Effect.ALLOW,
+                        principals=[iam.AccountPrincipal(ig_workspaces_account)],
+                        actions=["s3:ListBucket"],
+                        resources=[
+                            f"arn:aws:s3:{self.region}:{self.account}:accesspoint/egress-staging-bucket-access-point",
+                        ],
+                    ),
+                ]
+            )
 
         # Add dataset tags to bucket
         for tag_key, tag_value in self.node.try_get_context(env_id)["dataset"].items():
             Tags.of(egress_staging_bucket).add(tag_key, tag_value)
 
-        # Add Egress Target Bucket
-        egress_target_bucket = s3.Bucket(
-            self,
-            "Egress-Target-Bucket",
-            encryption=s3.BucketEncryption.KMS,
-            encryption_key=s3_kms_key,
-            enforce_ssl=True,
-            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
-            server_access_logs_bucket=access_logs_bucket,
-            server_access_logs_prefix="egress_target_logs",
-            versioned=True,
-            bucket_key_enabled=True,
-        )
+        if not datalake_target_provided:
+            # Add Egress Target Bucket
+            egress_target_bucket = s3.Bucket(
+                self,
+                "Egress-Target-Bucket",
+                encryption=s3.BucketEncryption.KMS,
+                encryption_key=s3_kms_key,
+                enforce_ssl=True,
+                block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
+                server_access_logs_bucket=access_logs_bucket,
+                server_access_logs_prefix="egress_target_logs",
+                versioned=True,
+                bucket_key_enabled=True,
+            )
+            egress_target_bucket_kms_key = s3_kms_key
 
         # Add Amplify App
         amplify_branch_name = "main"
@@ -952,7 +1010,7 @@ class EgressBackendStack(cdk.Stack):
             environment={
                 "EGRESS_STAGING_BUCKET": egress_staging_bucket.bucket_name,
                 "EGRESS_DATALAKE_BUCKET": egress_target_bucket.bucket_name,
-                "EGRESS_DATALAKE_BUCKET_KMS_KEY": s3_kms_key.key_arn,
+                "EGRESS_DATALAKE_BUCKET_KMS_KEY": egress_target_bucket_kms_key.key_arn,
                 "EFS_MOUNT_PATH": efs_mount_path + "/",  # Need the extra slash
                 "REGION": self.region,
             },
@@ -969,7 +1027,9 @@ class EgressBackendStack(cdk.Stack):
         s3_kms_key.grant_decrypt(copy_egress_candidates_to_datalake_function)
 
         # Grant copy lambda function permission to use KMS key of the datalake bucket
-        s3_kms_key.grant_encrypt_decrypt(copy_egress_candidates_to_datalake_function)
+        egress_target_bucket_kms_key.grant_encrypt_decrypt(
+            copy_egress_candidates_to_datalake_function
+        )
 
         # Grant copy lambda function permission to read/delete from egress staging bucket
         egress_staging_bucket.grant_read(copy_egress_candidates_to_datalake_function)
@@ -1151,10 +1211,9 @@ class EgressBackendStack(cdk.Stack):
             iam_action="ses:sendEmail",
         )
 
-        is_single_approval_enabled = (
-            self.node.try_get_context(env_id).get("enable_single_approval")
-            if self.node.try_get_context(env_id).get("enable_single_approval")
-            else "false"
+        # This is passed around the lambda so must be a string
+        is_single_approval_enabled = from_bool_string(
+            self.node.try_get_context(env_id).get("enable_single_approval"), str
         )
 
         # Define Egress Workflow Step Function
@@ -1305,6 +1364,9 @@ class EgressBackendStack(cdk.Stack):
                 "MAX_DOWNLOADS_ALLOWED": self.node.try_get_context(env_id).get(
                     "max_downloads_allowed"
                 ),
+                "DOWNLOAD_EXPIRY_SECONDS": self.node.try_get_context(env_id).get(
+                    "download_expiry_seconds"
+                ),
             },
         )
 
@@ -1731,6 +1793,14 @@ class EgressBackendStack(cdk.Stack):
             value=egress_app_url,
             description="The URL for the Egress App.",
         )
+
+        cdk.CfnOutput(
+            self,
+            "MaxDownloadsAllowed",
+            value=self.node.try_get_context(env_id).get("max_downloads_allowed"),
+            description="Max downloads allowed parameter provided.",
+        )
+
         for idx, role in enumerate(
             self.node.try_get_context(env_id).get("egress_reviewer_roles")
         ):
@@ -1798,9 +1868,10 @@ class EgressBackendStack(cdk.Stack):
             description="KMS Key ARN for egress staging s3 bucket",
         )
 
-        cdk.CfnOutput(
-            self,
-            "EgressStagingS3BucketAccessPointArn",
-            value=egress_staging_bucket_access_point.attr_arn,
-            description="Egress staging bucket access point arn",
-        )
+        if use_s3_access_points:
+            cdk.CfnOutput(
+                self,
+                "EgressStagingS3BucketAccessPointArn",
+                value=egress_staging_bucket_access_point.attr_arn,
+                description="Egress staging bucket access point arn",
+            )
```

</details>

**Comment by manics** [comment]
@AaronJackson would you mind taking another look at this? I haven't deployed it yet, but this should incorporate all changes from the TREEHOOSE and the HIC-TRE egress backends.

The main changes are mostly conditionals based on these `cdk.json` parameters:

- `datalake_target_bucket_arn` and `datalake_target_bucket_kms_arn`: TREEHOOSE assumes a DataLake S3 bucket already exists, HIC-TRE creates a new S3 bucket for the final egress
- `ig_workspaces_account`: Used by HIC-TRE but not TREEHOOSE though the code change is pretty minimal, just an addition to an S3 access policy, can you remember if there were any core SWB changes?
- `use_s3_access_points`: This is purely to support our custom SWB fork, it's of no use to anyone else
- `is_single_approval_enabled`: Removes the need for a second approval step as in the HIC-TRE, I think this should work in TREEHOOSE too since it shouldn't depend on SWB
- `download_expiry_seconds`: New in both, makes the pre-signed URL expiry configurable

**Review by AaronJackson — APPROVED** [review]
It all looks good to me 😀 it "runs" on my machine in the sense that it doesn't give any syntax warnings. The new downloads expiry variable seems properly referenced from cdk json.

**Comment by manics** [comment]
I've tested the dual approval workflow on TREEHOOSE. The single approval workflow won't work on TREEHOOSE until the frontend is also update, but I expect this backend to work with the HIC-TRE as long as the additional parameters are set.

**Comment by AaronJackson** [comment]
We'll merge this and do some testing against our staging environment with both the backend and frontend.

**Review by AaronJackson — APPROVED** [review]

**Pull request merged**
